// THIS FILE IS GENERATED - DO NOT MODIFY
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_FRAMEWORK_CLI_NAME = 'tnp';
/**
 *  This value can be change in taon.jsonc (appId)
 */
export const APP_ID = 'com.domain.example.vscode-plugin';
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_BASE_HREF = '';
/**
 *  This value can be change in taon.jsonc (overrideNpmName)
 */
export const PROJECT_NPM_NAME = '@taon-dev/vscode-plugin';
/**
 * Taon version from you project taon.json
 */
export const CURRENT_PACKAGE_TAON_VERSION = 'v21';
/**
 *  Autogenerated by current cli tool. Use *tnp release* to bump version.
 */
export const CURRENT_PACKAGE_VERSION = '21.0.3';





// THIS FILE IS GENERATED - DO NOT MODIFY
      